In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:\\Users\\Admin\\Desktop\\Data science\\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [6]:
df.shape

(5572, 3)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:14]

3403    An Amazing Quote'' - "Sometimes in life its di...
5414                                           East coast
3172               Still otside le..u come 2morrow maga..
2471    Eat at old airport road... But now 630 oredi.....
2800    I've told him that i've returned it. That shou...
2907    Helloooo... Wake up..! "Sweet" "morning" "welc...
1004        &lt;#&gt;  am I think? Should say on syllabus
3422    Welcome! Please reply with your AGE and GENDER...
696                  Good. Good job. I like entrepreneurs
2538            That's y we haf to combine n c how lor...
441     Yes..he is really great..bhaji told kallis bes...
3947    How u doin baby girl ?? hope u are okay every ...
4730                                I've reached already.
3440    awesome, how do I deal with the gate? Charles ...
Name: Message, dtype: object

In [13]:
X_train[0:14]

3403    An Amazing Quote'' - "Sometimes in life its di...
5414                                           East coast
3172               Still otside le..u come 2morrow maga..
2471    Eat at old airport road... But now 630 oredi.....
2800    I've told him that i've returned it. That shou...
2907    Helloooo... Wake up..! "Sweet" "morning" "welc...
1004        &lt;#&gt;  am I think? Should say on syllabus
3422    Welcome! Please reply with your AGE and GENDER...
696                  Good. Good job. I like entrepreneurs
2538            That's y we haf to combine n c how lor...
441     Yes..he is really great..bhaji told kallis bes...
3947    How u doin baby girl ?? hope u are okay every ...
4730                                I've reached already.
3440    awesome, how do I deal with the gate? Charles ...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

3403    0
5414    0
3172    0
2471    0
Name: spam, dtype: int64

In [16]:
type(X_train.values)

numpy.ndarray

Create bag of words representation using CountVectorizer

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7772 sparse matrix of type '<class 'numpy.int64'>'
	with 59081 stored elements in Compressed Sparse Row format>

In [37]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
X_train_cv.shape

(4457, 7772)

In [41]:
v.get_feature_names_out()[1771]

'chatlines'

In [45]:
v.get_feature_names_out()[171]


'09057039994'

In [47]:
v.vocabulary_

{'an': 969,
 'amazing': 949,
 'quote': 5570,
 'sometimes': 6342,
 'in': 3666,
 'life': 4122,
 'its': 3793,
 'difficult': 2341,
 'to': 6963,
 'decide': 2226,
 'whats': 7503,
 'wrong': 7656,
 'lie': 4120,
 'that': 6840,
 'brings': 1534,
 'smile': 6285,
 'or': 4997,
 'the': 6844,
 'truth': 7086,
 'tear': 6772,
 'east': 2532,
 'coast': 1892,
 'still': 6514,
 'otside': 5028,
 'le': 4072,
 'come': 1927,
 '2morrow': 412,
 'maga': 4329,
 'eat': 2536,
 'at': 1131,
 'old': 4951,
 'airport': 897,
 'road': 5832,
 'but': 1601,
 'now': 4864,
 '630': 597,
 'oredi': 5009,
 'got': 3217,
 'lot': 4233,
 'of': 4913,
 'pple': 5379,
 've': 7289,
 'told': 6980,
 'him': 3462,
 'returned': 5794,
 'it': 3785,
 'should': 6154,
 're': 5622,
 'order': 5005,
 'helloooo': 3423,
 'wake': 7388,
 'up': 7214,
 'sweet': 6682,
 'morning': 4606,
 'welcomes': 7483,
 'you': 7733,
 'enjoy': 2623,
 'this': 6880,
 'day': 2206,
 'with': 7577,
 'full': 3058,
 'joy': 3878,
 'gud': 3282,
 'mrng': 4631,
 'lt': 4269,
 'gt': 3276,
 'a

In [49]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
np.where(X_train_np[0]!=0)

(array([ 949,  969, 1534, 2226, 2341, 3666, 3793, 4120, 4122, 4997, 5570,
        6285, 6342, 6772, 6840, 6844, 6963, 7086, 7503, 7656], dtype=int64),)

In [57]:
X_train_np[0][1771]

0

In [59]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [61]:
X_test_cv = v.transform(X_test)

Evaluate Performance

In [66]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       962
           1       0.96      0.93      0.95       153

    accuracy                           0.99      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [68]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

Train the model using sklearn pipeline and reduce number of lines of code

In [71]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [73]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [75]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       962
           1       0.96      0.93      0.95       153

    accuracy                           0.99      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

