In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [29]:
one_hot("amazing restaurant",60)

[12, 14]

In [31]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[12, 21], [6, 4], [2, 6], [11, 21, 16], [20, 23, 15], [17, 21], [18, 23, 25], [10, 15], [10, 6], [11, 10]]


In [33]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[12 21  0  0]
 [ 6  4  0  0]
 [ 2  6  0  0]
 [11 21 16  0]
 [20 23 15  0]
 [17 21  0  0]
 [18 23 25  0]
 [10 15  0  0]
 [10  6  0  0]
 [11 10  0  0]]


In [35]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [37]:
X = padded_reviews
y = sentiment

In [39]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [41]:
model.fit(X, y, epochs=50, verbose=0)

In [42]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step - accuracy: 0.9000 - loss: 0.6235


0.8999999761581421

In [43]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [47]:
weights[13]

array([ 0.04241851, -0.0039211 ,  0.00253366, -0.049847  ,  0.0132804 ],
      dtype=float32)

In [49]:
weights[4]

array([-0.05637455, -0.08230197, -0.08813447, -0.0866017 ,  0.02445999],
      dtype=float32)

In [51]:
weights[16]

array([-0.05189218,  0.0971286 ,  0.00440966, -0.05250733, -0.07364599],
      dtype=float32)